"""add categories

Revision ID: 39587cc2be7a
Revises: d3070913257e
Create Date: 2026-02-15 21:45:19.193059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39587cc2be7a'
down_revision: Union[str, Sequence[str], None] = 'd3070913257e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('group', sa.String(length=80), nullable=True),
    sa.Column('subgroup', sa.String(length=80), nullable=True),
    sa.Column('default_debit_account_code', sa.String(length=30), nullable=True),
    sa.Column('default_credit_account_code', sa.String(length=30), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.add_column('transactions', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
